#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/normalize-card-quality.py
230개 명심카드 전수 정규화 및 품질 강화 스크립트
1. threeCodeHint 명시적 태깅 (Dark Code / Neural Code / Zero Point)
2. recommendedBook 및 책 직링크 매핑 정규화 (특히 제로 포인트 YES24 신규 링크)
3. 질문 및 사이다 답변의 불필요한 이중 따옴표 정리 및 종결어미 정돈
4. curiosityBridge / syncMessage / scanGuide alias 정규화
5. data/mind-cards.json, js/mind-cards-data.js, data/cards/ 동기화
"""

import json
import os
import re

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_FILE = os.path.join(BASE_DIR, "data", "mind-cards.json")
JS_DATA_FILE = os.path.join(BASE_DIR, "js", "mind-cards-data.js")
CARDS_DIR = os.path.join(BASE_DIR, "data", "cards")

YES24_LINKS = {
    "다크 코드": "https://www.yes24.com/product/goods/196721492",
    "뉴럴 코드": "https://www.yes24.com/Product/Search?domain=BOOK&query=%EB%89%B4%EB%9F%B4%20%EC%BD%94%EB%93%9C",
    "제로 포인트": "https://www.yes24.com/product/goods/195946431",
    "나는 믿는다 그러나 갇히지 않는다": "https://www.yes24.com/product/goods/196550353"
}

def clean_quotes(text):
    if not text:
        return ""
    text = text.strip()
    # Remove surrounding double quotes or smart quotes
    if (text.startswith('"') and text.endswith('"')) or (text.startswith('“') and text.endswith('”')):
        text = text[1:-1].strip()
    return text

def normalize_card(card):
    # 1. Clean Quotes
    card["question"] = clean_quotes(card.get("question", ""))
    card["sodaAnswer"] = clean_quotes(card.get("sodaAnswer", ""))
    card["tenPercentAction"] = clean_quotes(card.get("tenPercentAction", ""))
    card["syncSentence"] = clean_quotes(card.get("syncSentence", ""))
    card["shiftQuestion"] = clean_quotes(card.get("shiftQuestion", ""))
    card["curiosityQuestion"] = clean_quotes(card.get("curiosityQuestion", ""))
    
    # 2. relatedBook & recommendedBook
    rel_book = card.get("relatedBook", "")
    if not rel_book:
        rel_book = "다크 코드"
        
    if "다크" in rel_book:
        canonical_book = "다크 코드"
        hint = "Dark Code"
    elif "뉴럴" in rel_book:
        canonical_book = "뉴럴 코드"
        hint = "Neural Code"
    elif "제로" in rel_book:
        canonical_book = "제로 포인트"
        hint = "Zero Point"
    elif "믿는다" in rel_book:
        canonical_book = "나는 믿는다 그러나 갇히지 않는다"
        hint = "Zero Point"
    else:
        canonical_book = "다크 코드"
        hint = "Dark Code"
        
    card["relatedBook"] = canonical_book
    card["recommendedBook"] = canonical_book
    card["threeCodeHint"] = card.get("threeCodeHint") or hint
    card["bookLink"] = YES24_LINKS.get(canonical_book, "https://www.yes24.com/Product/Search?domain=BOOK&query=%EC%B2%AD%EB%A5%98%EC%B6%9C%ED%8C%90%EC%82%AC")
    
    # 3. Aliases
    card["curiosityBridge"] = card.get("curiosityBridge") or card["curiosityQuestion"]
    card["syncMessage"] = card.get("syncMessage") or card["syncSentence"]
    
    # 4. 1-minute SCAN guide structure
    card["scanGuide"] = {
        "step1": card.get("factQuestion", "실제로 확인된 사실(FACT)은 무엇인가요?"),
        "step2": card.get("storyQuestion", "그 사실에 내가 붙인 해석(STORY)은 무엇인가요?"),
        "step3": card.get("unknownQuestion", "아직 확인되지 않은 영역(UNKNOWN)은 무엇인가요?"),
        "step4": card.get("bodyQuestion", "몸에서는 어디가 먼저 반응하고 있나요?")
    }
    
    # 5. Question ending polish
    q = card["question"]
    if not (q.endswith("?") or q.endswith("요") or q.endswith("까")):
        card["question"] = q + "?"
        
    # 6. Related cards limit to max 2 for anti-loop
    rel_cards = card.get("relatedCards", [])
    if isinstance(rel_cards, list) and len(rel_cards) > 2:
        card["relatedCards"] = rel_cards[:2]
        
    return card

def main():
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        cards = json.load(f)
        
    print(f"Normalizing {len(cards)} cards...")
    normalized = [normalize_card(c) for c in cards]
    
    # Write back to mind-cards.json
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(normalized, f, ensure_ascii=False, indent=2)
    print(f"Saved {DATA_FILE}")
    
    # Write to js/mind-cards-data.js
    js_content = f"// MindflowLab Canonical Mind Cards Dataset (Total {len(normalized)} Cards)\n"
    js_content += f"// Generated by scripts/normalize-card-quality.py\n\n"
    js_content += f"window.MIND_CARDS_DATA = {json.dumps(normalized, ensure_ascii=False, indent=2)};\n"
    with open(JS_DATA_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)
    print(f"Saved {JS_DATA_FILE}")
    
    # Split into data/cards/ categories
    os.makedirs(CARDS_DIR, exist_ok=True)
    categories = {
        "relationship.json": ["관계·심리", "경계와 관계"],
        "money.json": ["돈·사업실패·빚", "생존·불안"],
        "career.json": ["번아웃·이직퇴사·성과", "에너지와 번아웃", "성취·일"],
        "perfection.json": ["완벽주의·인정욕구·비교", "완벽주의와 통제"],
        "family.json": ["부모원망·가족독립"],
        "love.json": ["연애애착·이별·친밀감"],
        "decision.json": ["결정·미루기·습관", "변화와 시도"],
        "emotion.json": ["유리멘탈·자책·불안", "감정 민감성", "불안과 방어", "생각 과열"],
        "belief.json": ["사주미신·삼재·운명역전", "불확실성"],
        "three-code.json": ["3대코드·제로포인트", "정체성과 관찰"],
        "foundation.json": [] # base 30
    }
    
    for filename, cats in categories.items():
        if filename == "foundation.json":
            matched = normalized[:30]
        else:
            matched = [c for c in normalized if c.get("category") in cats]
        filepath = os.path.join(CARDS_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(matched, f, ensure_ascii=False, indent=2)
            
    print("All category datasets in data/cards/ updated successfully.")

if __name__ == "__main__":
    main()
