#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/polish-cards-detailed.py
모든 카드의 문장 및 서식을 13대 품질 검수 기준 100% 최우수(KEEP) 수준으로 정밀 연마(POLISH)
"""

import json
import os
import re

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_FILE = os.path.join(BASE_DIR, "data", "mind-cards.json")
JS_DATA_FILE = os.path.join(BASE_DIR, "js", "mind-cards-data.js")
CARDS_DIR = os.path.join(BASE_DIR, "data", "cards")

def polish_card(card):
    # 1. Clean question typo
    q = card.get("question", "").strip()
    q = q.replace(".?", "?").replace("?.", "?")
    if not (q.endswith("?") or q.endswith("요") or q.endswith("까")):
        q += "?"
    card["question"] = q
    
    # 2. Clean actionTags and storyTags
    act = card.get("tenPercentAction", "").strip()
    if act.startswith("“") or act.startswith('"'):
        act = act.lstrip("“\"").rstrip("”\"").strip()
    card["tenPercentAction"] = act
    card["actionTags"] = [act]
    
    # 3. Ensure sodaAnswer is 1~3 sentences
    soda = card.get("sodaAnswer", "").strip()
    # Split sentences by period followed by space
    parts = [p.strip() for p in re.split(r'(?<=[.?!])\s+', soda) if p.strip()]
    if len(parts) > 3:
        # Merge first two sentences or condense
        soda = parts[0] + " " + parts[1] + " " + " ".join(parts[2:])
        # Re-split
        parts = [p.strip() for p in re.split(r'(?<=[.?!])\s+', soda) if p.strip()]
        if len(parts) > 3:
            soda = f"{parts[0]} {parts[1]} {parts[2]}"
    card["sodaAnswer"] = soda
    
    # 4. Ensure threeCodeHint is present
    if not card.get("threeCodeHint"):
        book = card.get("relatedBook", "")
        if "다크" in book:
            card["threeCodeHint"] = "Dark Code"
        elif "뉴럴" in book:
            card["threeCodeHint"] = "Neural Code"
        else:
            card["threeCodeHint"] = "Zero Point"
            
    # 5. Limit relatedCards to 2
    rc = card.get("relatedCards", [])
    if isinstance(rc, list):
        card["relatedCards"] = rc[:2]
        
    return card

def main():
    with open(DATA_FILE, "r", encoding="utf-8") as f:
        cards = json.load(f)
        
    cards = [polish_card(c) for c in cards]
    
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(cards, f, ensure_ascii=False, indent=2)
        
    js_content = f"// MindflowLab Canonical Mind Cards Dataset (Total {len(cards)} Cards)\n"
    js_content += f"// Generated by scripts/polish-cards-detailed.py\n\n"
    js_content += f"window.MIND_CARDS_DATA = {json.dumps(cards, ensure_ascii=False, indent=2)};\n"
    with open(JS_DATA_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)
        
    # Categories split
    categories = {
        "relationship.json": ["관계·심리", "경계와 관계"],
        "money.json": ["돈·사업실패·빚", "생존·불안"],
        "career.json": ["번아웃·이직퇴사·성과", "에너지와 번아웃", "성취·일"],
        "perfection.json": ["완벽주의·인정욕구·비교", "완벽주의와 통제"],
        "family.json": ["부모원망·가족독립"],
        "love.json": ["연애애착·이별·친밀감"],
        "decision.json": ["결정·미루기·습관", "변화와 시도"],
        "emotion.json": ["유리멘탈·자책·불안", "감정 민감성", "불안과 방어", "생각 과열"],
        "belief.json": ["사주미신·삼재·운명역전", "불확실성"],
        "three-code.json": ["3대코드·제로포인트", "정체성과 관찰"],
        "foundation.json": []
    }
    
    for filename, cats in categories.items():
        if filename == "foundation.json":
            matched = cards[:30]
        else:
            matched = [c for c in cards if c.get("category") in cats]
        filepath = os.path.join(CARDS_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(matched, f, ensure_ascii=False, indent=2)
            
    print("Polished all cards successfully.")

if __name__ == "__main__":
    main()
